### create user
POST http://localhost:3000/user-api/users
Content-Type: application/json

{
    "name":"varshini",
    "email":"varsh@gamil.com",
    "DOB":"12-12-2005",
    "mobileNo":"235698742"
}
### read all users
GET http://localhost:3000/user-api/users
### read a user by id
GET http://localhost:3000/user-api/users/69a6906a228b89b2ef457461
### delete a user by id
DELETE http://localhost:3000/user-api/users/69a683d29ae6326a5d413620
### activate user
PATCH http://localhost:3000/user-api/users/69a683d29ae6326a5d413620