# user register 
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "firstname":"gatla",
    "lastname":"varsh",
    "email":"varsh@example.com",
    "password":"varsh123",
    "profileImageUrl":"https://example.com/avaters/author.png"
}

### author register
POST http://localhost:4000/author-api/users
Content-Type: application/json

{
    "firstname":"G",
    "lastname":"sanjana",
    "email":"sanjana@example.com",
    "password":"sanjana123",
    "profileImageUrl":"https://example.com/avaters/author.png"
}

### crteate article (author)
POST http://localhost:4000/author-api/articles
Content-Type: application/json

{
    "author":"69897a149a24e6bde3b79083",
    "title":"test2 article",
    "category":"programming",
    "content":"content of test2 article"
}
### read article content
GET http://localhost:4000/author-api/article/69897a149a24e6bde3b79083

### update article 
PUT http://localhost:4000/author-api/articles
Content-Type: application/json

{
    "author":"69897a149a24e6bde3b79083",
    "articleid":"69898fdc6e288cc50b6aa352",
    "title":"test1 article",
    "category":"programming",
    "content":"test1 article content"
}
### delete the article
DELETE http://localhost:4000/author-api/article/698aa5514bed263eda6466f7/author/69897a149a24e6bde3b79083


### logout
GET http://localhost:4000/common-api/logout

### read articles from the user
GET http://localhost:4000/user-api/articles
### add comments 
PUT http://localhost:4000/user-api/articles/69898fdc6e288cc50b6aa352
Content-Type: application/json

{
    "author":"69897a149a24e6bde3b79083",
    "comment":"good"
}

### login(common)
GET http://localhost:4000/common-api/login
Content-Type: application/json

{
    "email":"varshini@example.com",
    "password":"gatla123"
}
### 
GET http://localhost:4000/test

### block by admin
PUT http://localhost:4000/admin-api/block/69896c52121d0acf0aa80faa
### unblock by admin
PUT http://localhost:4000/admin-api/unblock/69896c52121d0acf0aa80faa
### change password
PUT http://localhost:4000/common-api/change-password
Content-Type: application/json

{
    "email":"sanjana@example.com",
    "oldpassword":"sanjana123",
    "newpassword":"sanju123"
}