GET http://localhost:3000/product-api/products

###
POST http://localhost:3000/product-api/products
Content-Type: application/json

{
    "productname":"modile",
    "price":10000,
    "brand":"1+"
}

###
POST http://localhost:3000/user-api/users
Content-Type: application/json

{
    "name":"gatla varshini",
    "email":"gatla@gmail.com",
    "password":"gatla",
    "cart":[]
}

### req to add product into uset cart
PUT http://localhost:3000/user-api/user-cart/user-id/6981a66173d2aeb938776b1d/product-id/698072514e787438c1f45ad0

### read user by id
GET http://localhost:3000/user-api/users/6981a66173d2aeb938776b1d